<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Homeproduction_model extends CI_Model
{

    public $table = 'homeproduction';
    public $id = 'id_homeproduction';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_homeproduction', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('pemilik', $q);
	$this->db->or_like('tahun_berdiri', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('no_tlp', $q);
	$this->db->or_like('logo', $q);
	$this->db->or_like('website', $q);
	$this->db->or_like('instagram', $q);
	$this->db->or_like('facebook', $q);
	$this->db->or_like('twitter', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_homeproduction', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('pemilik', $q);
	$this->db->or_like('tahun_berdiri', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('no_tlp', $q);
	$this->db->or_like('logo', $q);
	$this->db->or_like('website', $q);
	$this->db->or_like('instagram', $q);
	$this->db->or_like('facebook', $q);
	$this->db->or_like('twitter', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Homeproduction_model.php */
/* Location: ./application/models/Homeproduction_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-02-08 08:31:43 */
/* http://harviacode.com */